In [221]:
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns
import numpy as np
import pandas as pd
import scipy

In [285]:
def CntLags(df, column, n_lags=15):
    df[f'{column}_lag1'] = df[column]

    for lag in range(2, n_lags + 1):
        df[f'{column}_lag{lag}'] = [0] * df.shape[0]
    
    for lag in range(1, n_lags):
        df[f'{column}_lag{lag + 1}'] = [0] * lag + list(df[column][:-lag])
    
    if n_lags >= 5:
        df[f'{column}_mean5'] = np.mean([df[f'{column}_lag1'], df[f'{column}_lag2'], df[f'{column}_lag3'], df[f'{column}_lag4'], df[f'{column}_lag5']], axis = 0)
    if n_lags >= 10:
        df[f'{column}_mean10'] = np.mean([df[f'{column}_lag1'], df[f'{column}_lag2'], df[f'{column}_lag3'], df[f'{column}_lag4'], df[f'{column}_lag5'],
                                df[f'{column}_lag6'], df[f'{column}_lag7'], df[f'{column}_lag8'], df[f'{column}_lag9'], df[f'{column}_lag10'],], axis = 0)
    if n_lags >= 15:
        df[f'{column}_mean15'] = np.mean([df[f'{column}_lag1'], df[f'{column}_lag2'], df[f'{column}_lag3'], df[f'{column}_lag4'], df[f'{column}_lag5'],
                                df[f'{column}_lag6'], df[f'{column}_lag7'], df[f'{column}_lag8'], df[f'{column}_lag9'], df[f'{column}_lag10'],
                                df[f'{column}_lag11'], df[f'{column}_lag12'], df[f'{column}_lag13'], df[f'{column}_lag14'], df[f'{column}_lag15'],], axis = 0)

    return df

In [286]:
blocks_info = pd.read_csv('blocks_info.csv')

blocks_info['time'] = pd.to_datetime(blocks_info['time'])
blocks_info = blocks_info.sort_values(by='time').reset_index()
blocks_info = blocks_info.drop(columns=['index', 'id'])
blocks_info

,time,size,transaction_count,input_count,output_count,input_total,input_total_usd,fee_total,fee_total_usd,fee_per_kb,fee_per_kb_usd,reward,reward_usd,guessed_miner,time_between_blocks
0,2021-01-01 00:03:56,1309398,1304,6839,3908,369444589181,107220208.0,61883190,17959.7402,47275.200,13.7202,686883190,199347.2344,ViaBTC,NaN
1,2021-01-01 00:16:15,1352818,2485,6189,7970,1704421384387,494657184.0,44406127,12887.5459,32832.800,9.5288,669406127,194275.0469,Bitdeer,739.0
2,2021-01-01 00:17:06,2277472,293,7048,636,25386204929,7367584.5,5575852,1618.2238,2448.630,0.7107,630575852,183005.7188,1THash&58COIN,51.0
3,2021-01-01 00:24:45,1562499,1410,6717,3968,2838244301588,823715264.0,30387514,8819.0645,19453.300,5.6456,655387514,190206.5625,BTC.com,459.0
4,2021-01-01 00:34:46,1454916,1674,7137,5260,213733200927,62029648.0,40234409,11676.8301,27662.400,8.0281,665234409,193064.3281,AntPool,601.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120917,2023-04-10 22:18:16,1369265,2637,5539,11822,1541614071623,437063008.0,43165504,12237.8516,31531.420,8.9394,668165504,189431.6094,Binance,2437.0
120918,2023-04-10 22:18:21,1429261,2523,7246,6389,643778311390,182517584.0,22329479,6330.6304,15627.358,4.4304,647329479,183524.3750,AntPool,5.0
120919,2023-04-10 23:21:50,1448278,2874,5671,14774,2262268881146,641375872.0,44272986,12551.8340,30577.611,8.6692,669272986,189745.5781,AntPool,3809.0
120920,2023-04-10 23:36:08,1401931,2779,6655,8590,1156441780657,327862816.0,31925271,9051.1338,22778.676,6.4581,656925271,186244.8906,AntPool,858.0
120921,2023-04-10 23:52:12,1517436,3586,6332,12376,1468037906488,416203424.0,29506112,8365.2773,19449.701,5.5143,654506112,185559.0312,AntPool,964.0

In [287]:
df = pd.read_csv('binance_data.csv')
df['Open time'] = pd.to_datetime(df['Open time'])
df['Close time'] = pd.to_datetime(df['Close time'])
df = df.sort_values(by='Open time').reset_index()
df = df.drop(columns=['index'])
df

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume
0,2020-12-31 21:00:00,29126.71,29140.00,28968.98,28993.20,352.397377,2020-12-31 21:04:59.999,1.023407e+07,6651,123.969773,3.598840e+06
1,2020-12-31 21:05:00,28992.70,28994.17,28900.79,28994.16,213.453155,2020-12-31 21:09:59.999,6.180498e+06,4458,79.862216,2.312485e+06
2,2020-12-31 21:10:00,28994.17,29041.95,28976.68,29039.12,127.869947,2020-12-31 21:14:59.999,3.709233e+06,2857,52.528098,1.523780e+06
3,2020-12-31 21:15:00,29039.13,29145.00,29029.33,29143.06,230.412047,2020-12-31 21:19:59.999,6.702830e+06,5085,122.864715,3.574664e+06
4,2020-12-31 21:20:00,29143.05,29143.79,29051.00,29080.33,272.211005,2020-12-31 21:24:59.999,7.920284e+06,4826,80.304665,2.336602e+06
...,...,...,...,...,...,...,...,...,...,...,...
238995,2023-04-10 17:15:00,29134.02,29207.50,29063.19,29080.51,724.669050,2023-04-10 17:19:59.999,2.112116e+07,14559,356.109320,1.038025e+07
238996,2023-04-10 17:20:00,29080.52,29106.16,29011.17,29030.00,968.516860,2023-04-10 17:24:59.999,2.813805e+07,15710,409.284180,1.189011e+07
238997,2023-04-10 17:25:00,29030.00,29149.99,29024.79,29100.67,657.486850,2023-04-10 17:29:59.999,1.913244e+07,11474,324.711390,9.447418e+06
238998,2023-04-10 17:30:00,29100.67,29380.00,29100.66,29135.28,1294.376660,2023-04-10 17:34:59.999,3.783723e+07,24077,770.461910,2.252938e+07
238999,2023-04-10 17:35:00,29135.27,29175.54,29044.70,29080.00,507.192790,2023-04-10 17:39:59.999,1.475616e+07,11046,256.476870,7.461424e+06

In [288]:
blocks_info_columns = ['transaction_count', 'input_count', 'output_count', 'input_total_usd', 'fee_total_usd', 'fee_per_kb_usd', 'reward_usd', 'time_between_blocks']

In [289]:
# for column in blocks_info_columns:
#     if column == 'time_between_blocks':
#         continue
#     blocks_info[column] = blocks_info[column] / times

In [290]:
for column in blocks_info_columns:
    df[column] = [0]*df.shape[0]

In [291]:
from tqdm import tqdm

In [292]:
ind = 0
for i in tqdm(range(df.shape[0])):
    while df.loc[i, 'Open time'] > blocks_info.loc[ind, 'time']:
        ind += 1
    for column in blocks_info_columns:
        df.loc[i, column] = blocks_info.loc[ind, column]

100%|██████████| 239000/239000 [09:14<00:00, 431.27it/s]

In [293]:
df['time_between_blocks'] = df['time_between_blocks'].fillna(df['time_between_blocks'].mean())
df

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,transaction_count,input_count,output_count,input_total_usd,fee_total_usd,fee_per_kb_usd,reward_usd,time_between_blocks
0,2020-12-31 21:00:00,29126.71,29140.00,28968.98,28993.20,352.397377,2020-12-31 21:04:59.999,1.023407e+07,6651,123.969773,3.598840e+06,1304,6839,3908,1.072202e+08,17959.7402,13.7202,199347.2344,1194.138603
1,2020-12-31 21:05:00,28992.70,28994.17,28900.79,28994.16,213.453155,2020-12-31 21:09:59.999,6.180498e+06,4458,79.862216,2.312485e+06,1304,6839,3908,1.072202e+08,17959.7402,13.7202,199347.2344,1194.138603
2,2020-12-31 21:10:00,28994.17,29041.95,28976.68,29039.12,127.869947,2020-12-31 21:14:59.999,3.709233e+06,2857,52.528098,1.523780e+06,1304,6839,3908,1.072202e+08,17959.7402,13.7202,199347.2344,1194.138603
3,2020-12-31 21:15:00,29039.13,29145.00,29029.33,29143.06,230.412047,2020-12-31 21:19:59.999,6.702830e+06,5085,122.864715,3.574664e+06,1304,6839,3908,1.072202e+08,17959.7402,13.7202,199347.2344,1194.138603
4,2020-12-31 21:20:00,29143.05,29143.79,29051.00,29080.33,272.211005,2020-12-31 21:24:59.999,7.920284e+06,4826,80.304665,2.336602e+06,1304,6839,3908,1.072202e+08,17959.7402,13.7202,199347.2344,1194.138603
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238995,2023-04-10 17:15:00,29134.02,29207.50,29063.19,29080.51,724.669050,2023-04-10 17:19:59.999,2.112116e+07,14559,356.109320,1.038025e+07,3390,6451,11413,1.482038e+09,7949.7964,5.3909,185143.5469,1369.000000
238996,2023-04-10 17:20:00,29080.52,29106.16,29011.17,29030.00,968.516860,2023-04-10 17:24:59.999,2.813805e+07,15710,409.284180,1.189011e+07,3390,6451,11413,1.482038e+09,7949.7964,5.3909,185143.5469,1369.000000
238997,2023-04-10 17:25:00,29030.00,29149.99,29024.79,29100.67,657.486850,2023-04-10 17:29:59.999,1.913244e+07,11474,324.711390,9.447418e+06,3390,6451,11413,1.482038e+09,7949.7964,5.3909,185143.5469,1369.000000
238998,2023-04-10 17:30:00,29100.67,29380.00,29100.66,29135.28,1294.376660,2023-04-10 17:34:59.999,3.783723e+07,24077,770.461910,2.252938e+07,3039,5943,12693,6.493320e+08,9779.9922,6.7246,186973.7500,2148.000000
238999,2023-04-10 17:35:00,29135.27,29175.54,29044.70,29080.00,507.192790,2023-04-10 17:39:59.999,1.475616e+07,11046,256.476870,7.461424e+06,3039,5943,12693,6.493320e+08,9779.9922,6.7246,186973.7500,2148.000000

In [294]:
df_columns = ['Open', 'High', 'Low', 'Close', 'Volume', 'Quote asset volume', 'Number of trades', 'Taker buy base asset volume', 'Taker buy quote asset volume']
columns = df_columns + blocks_info_columns

In [295]:
df_lookback = df.drop(columns=['Open time', 'Close time'])
orig_shape = df_lookback.shape

lookback = 15

lookback_columns = [df_lookback.shift(i) for i in range(lookback)]
df_lookback = pd.concat(lookback_columns, axis=1)

df_lookback = df_lookback.values.reshape(orig_shape[0], lookback, orig_shape[1])
df_lookback.shape, df.shape

((239000, 15, 17), (239000, 19))

In [296]:
df_lookback=df_lookback[lookback:]
df_lookback[0]

array([[2.90705800e+04, 2.90817400e+04, 2.90631900e+04, 2.90702700e+04,
        1.34890576e+02, 3.92179705e+06, 2.06100000e+03, 3.74305240e+01,
        1.08826270e+06, 1.30400000e+03, 6.83900000e+03, 3.90800000e+03,
        1.07220208e+08, 1.79597402e+04, 1.37202000e+01, 1.99347234e+05,
        1.19413860e+03],
       [2.89879200e+04, 2.90710000e+04, 2.89625800e+04, 2.90705800e+04,
        1.33987702e+02, 3.88678450e+06, 2.65100000e+03, 6.05722290e+01,
        1.75770827e+06, 1.30400000e+03, 6.83900000e+03, 3.90800000e+03,
        1.07220208e+08, 1.79597402e+04, 1.37202000e+01, 1.99347234e+05,
        1.19413860e+03],
       [2.89800100e+04, 2.89953600e+04, 2.89101900e+04, 2.89879200e+04,
        1.54161591e+02, 4.46291688e+06, 3.55700000e+03, 5.20294930e+01,
        1.50630499e+06, 1.30400000e+03, 6.83900000e+03, 3.90800000e+03,
        1.07220208e+08, 1.79597402e+04, 1.37202000e+01, 1.99347234e+05,
        1.19413860e+03],
       [2.89663600e+04, 2.90414100e+04, 2.89663600e+04, 2.89800100e+04,
        1.46733770e+02, 4.25628676e+06, 3.06200000e+03, 6.84266630e+01,
        1.98485433e+06, 1.30400000e+03, 6.83900000e+03, 3.90800000e+03,
        1.07220208e+08, 1.79597402e+04, 1.37202000e+01, 1.99347234e+05,
        1.19413860e+03],
       [2.90106100e+04, 2.90357900e+04, 2.89501000e+04, 2.89663600e+04,
        1.59748747e+02, 4.63057725e+06, 3.29600000e+03, 5.67994050e+01,
        1.64680404e+06, 1.30400000e+03, 6.83900000e+03, 3.90800000e+03,
        1.07220208e+08, 1.79597402e+04, 1.37202000e+01, 1.99347234e+05,
        1.19413860e+03],
       [2.90091200e+04, 2.90821200e+04, 2.89824000e+04, 2.90106200e+04,
        1.85616625e+02, 5.39076816e+06, 3.95300000e+03, 5.98795420e+01,
        1.73913589e+06, 1.30400000e+03, 6.83900000e+03, 3.90800000e+03,
        1.07220208e+08, 1.79597402e+04, 1.37202000e+01, 1.99347234e+05,
        1.19413860e+03],
       [2.90407800e+04, 2.90407900e+04, 2.89650000e+04, 2.90091200e+04,
        2.27158526e+02, 6.58754712e+06, 4.47300000e+03, 8.24750680e+01,
        2.39182777e+06, 1.30400000e+03, 6.83900000e+03, 3.90800000e+03,
        1.07220208e+08, 1.79597402e+04, 1.37202000e+01, 1.99347234e+05,
        1.19413860e+03],
       [2.90370000e+04, 2.90795000e+04, 2.90265700e+04, 2.90407800e+04,
        1.28157659e+02, 3.72374763e+06, 2.95300000e+03, 4.33696360e+01,
        1.26006000e+06, 1.30400000e+03, 6.83900000e+03, 3.90800000e+03,
        1.07220208e+08, 1.79597402e+04, 1.37202000e+01, 1.99347234e+05,
        1.19413860e+03],
       [2.91611700e+04, 2.91611800e+04, 2.90255400e+04, 2.90370000e+04,
        1.71365077e+02, 4.98506556e+06, 4.22000000e+03, 4.21470560e+01,
        1.22616032e+06, 1.30400000e+03, 6.83900000e+03, 3.90800000e+03,
        1.07220208e+08, 1.79597402e+04, 1.37202000e+01, 1.99347234e+05,
        1.19413860e+03],
       [2.90947100e+04, 2.91695500e+04, 2.90947100e+04, 2.91611700e+04,
        3.43905925e+02, 1.00227636e+07, 5.47400000e+03, 2.19368319e+02,
        6.39329503e+06, 1.30400000e+03, 6.83900000e+03, 3.90800000e+03,
        1.07220208e+08, 1.79597402e+04, 1.37202000e+01, 1.99347234e+05,
        1.19413860e+03],
       [2.90803400e+04, 2.91100000e+04, 2.90794200e+04, 2.90947100e+04,
        1.12177021e+02, 3.26407830e+06, 3.05100000e+03, 4.63240660e+01,
        1.34782885e+06, 1.30400000e+03, 6.83900000e+03, 3.90800000e+03,
        1.07220208e+08, 1.79597402e+04, 1.37202000e+01, 1.99347234e+05,
        1.19413860e+03],
       [2.91430500e+04, 2.91437900e+04, 2.90510000e+04, 2.90803300e+04,
        2.72211005e+02, 7.92028383e+06, 4.82600000e+03, 8.03046650e+01,
        2.33660226e+06, 1.30400000e+03, 6.83900000e+03, 3.90800000e+03,
        1.07220208e+08, 1.79597402e+04, 1.37202000e+01, 1.99347234e+05,
        1.19413860e+03],
       [2.90391300e+04, 2.91450000e+04, 2.90293300e+04, 2.91430600e+04,
        2.30412047e+02, 6.70282953e+06, 5.08500000e+03, 1.22864715e+02,
        3.57466427e+06, 1.30400000e+03, 6.83900000e+03, 3.90800000e+03,
        1.07220208e+08, 1.79597402e+04, 1.37202000e+01, 1.99347234e+05,
        1.19413860e+03],
       [2.89941700e+04, 2.90419500e+04, 2.89766800e+04, 2.90391200e+04,
        1.27869947e+02, 3.70923260e+06, 2.85700000e+03, 5.25280980e+01,
        1.52378010e+06, 1.30400000e+03, 6.83900000e+03, 3.90800000e+03,
        1.07220208e+08, 1.79597402e+04, 1.37202000e+01, 1.99347234e+05,
        1.19413860e+03],
       [2.89927000e+04, 2.89941700e+04, 2.89007900e+04, 2.89941600e+04,
        2.13453155e+02, 6.18049830e+06, 4.45800000e+03, 7.98622160e+01,
        2.31248535e+06, 1.30400000e+03, 6.83900000e+03, 3.90800000e+03,
        1.07220208e+08, 1.79597402e+04, 1.37202000e+01, 1.99347234e+05,
        1.19413860e+03]])

In [297]:
np.save('loockback_data.npz', df_lookback)

In [ ]:
tmp = pd.DataFrame()
tmp['f'] = df['High']
tmp['s'] = list(df['High'][1:]) + [0]
tmp['t'] = list(df['High'][2:]) + [0, 0]

df['Target'] = tmp.max(axis=1)

In [ ]:
df.to_csv('combined_data.csv', index=False)

In [ ]:
df = pd.read_csv('combined_data.csv')

In [216]:
for column in tqdm(df_columns):
    df = CntLags(df, column)

100%|██████████| 9/9 [00:08<00:00,  1.08it/s]

In [217]:
df

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,...,Taker buy quote asset volume_lag9,Taker buy quote asset volume_lag10,Taker buy quote asset volume_lag11,Taker buy quote asset volume_lag12,Taker buy quote asset volume_lag13,Taker buy quote asset volume_lag14,Taker buy quote asset volume_lag15,Taker buy quote asset volume_mean5,Taker buy quote asset volume_mean10,Taker buy quote asset volume_mean15
0,2020-12-31 21:00:00,29126.71,29140.00,28968.98,28993.20,352.397377,2020-12-31 21:04:59.999,1.023407e+07,6651,123.969773,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,7.197681e+05,3.598840e+05,2.399227e+05
1,2020-12-31 21:05:00,28992.70,28994.17,28900.79,28994.16,213.453155,2020-12-31 21:09:59.999,6.180498e+06,4458,79.862216,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.182265e+06,5.911326e+05,3.940884e+05
2,2020-12-31 21:10:00,28994.17,29041.95,28976.68,29039.12,127.869947,2020-12-31 21:14:59.999,3.709233e+06,2857,52.528098,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.487021e+06,7.435106e+05,4.956737e+05
3,2020-12-31 21:15:00,29039.13,29145.00,29029.33,29143.06,230.412047,2020-12-31 21:19:59.999,6.702830e+06,5085,122.864715,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.201954e+06,1.100977e+06,7.339847e+05
4,2020-12-31 21:20:00,29143.05,29143.79,29051.00,29080.33,272.211005,2020-12-31 21:24:59.999,7.920284e+06,4826,80.304665,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.669274e+06,1.334637e+06,8.897581e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238995,2023-04-10 17:15:00,29134.02,29207.50,29063.19,29080.51,724.669050,2023-04-10 17:19:59.999,2.112116e+07,14559,356.109320,...,4.468652e+06,8.309330e+06,2.063527e+06,2.208642e+06,2.046420e+06,2.464342e+06,7.786091e+06,2.412245e+07,2.218724e+07,1.589609e+07
238996,2023-04-10 17:20:00,29080.52,29106.16,29011.17,29030.00,968.516860,2023-04-10 17:24:59.999,2.813805e+07,15710,409.284180,...,1.464392e+07,4.468652e+06,8.309330e+06,2.063527e+06,2.208642e+06,2.046420e+06,2.464342e+06,1.803828e+07,2.254531e+07,1.616969e+07
238997,2023-04-10 17:25:00,29030.00,29149.99,29024.79,29100.67,657.486850,2023-04-10 17:29:59.999,1.913244e+07,11474,324.711390,...,2.961315e+07,1.464392e+07,4.468652e+06,8.309330e+06,2.063527e+06,2.208642e+06,2.046420e+06,1.427170e+07,2.304319e+07,1.663523e+07
238998,2023-04-10 17:30:00,29100.67,29380.00,29100.66,29135.28,1294.376660,2023-04-10 17:34:59.999,3.783723e+07,24077,770.461910,...,4.422507e+07,2.961315e+07,1.464392e+07,4.468652e+06,8.309330e+06,2.063527e+06,2.208642e+06,1.413807e+07,2.383174e+07,1.800076e+07
238999,2023-04-10 17:35:00,29135.27,29175.54,29044.70,29080.00,507.192790,2023-04-10 17:39:59.999,1.475616e+07,11046,256.476870,...,4.231095e+07,4.422507e+07,2.961315e+07,1.464392e+07,4.468652e+06,8.309330e+06,2.063527e+06,1.234172e+07,2.161656e+07,1.835095e+07

In [ ]:
df = df.drop(columns=columns)

In [219]:
df.to_csv('data_new.csv', index=False)